name: Test

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    test:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v3.3.0
              with:
                  fetch-depth: 1
                  submodules: false
            - name: Upgrade bash on Mac
              if: runner.os == 'macOs'
              run: brew install bash
            - name: Install oh-my-bash
              shell: bash
              run: bash --noprofile --norc -i "$PWD/.github/workflows/test.sh"
